---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: bretfisher/wordsmith-api
    newName: ghcr.io/groupanized/wordsmith-api
    newTag: gha-5575175539
  - name: bretfisher/wordsmith-web
    newName: ghcr.io/groupanized/wordsmith-web
    newTag: stable-20230717-cf40ba3
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
